config/routes.rb
Rails.application.routes.draw do

  root :to => 'session#new'

  # get 'session/new'
  # Session (login form/form submit/logout) routes:
  get '/login' => 'session#new' #login form
  post '/login' => 'session#create' #form submit, check credentials, create session
  delete '/login' => 'session#destroy' #logout (delete session)


  post '/orders/:id/accept' => 'orders#accept', as:'order_accept' #

  resources :users

  resources :orders

  resources :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :order, optional: true

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :patient, class_name: 'User', optional: true
  belongs_to :technician, class_name: 'User', optional: true

  has_many :comments


  # enum item_size: [:regular, :large]

  enum status: [:quoted, :pending_delivery, :delivered, :picked_up, :invoiced, :invoice_paid]

end

app/models/user.rb
class User < ApplicationRecord

  has_many :assigned_orders, class_name: 'Order', foreign_key: 'technician_id'
  has_many :submitted_orders, class_name: 'Order', foreign_key: 'patient_id'

  has_secure_password

  enum user_type: [:patient, :technician, :admin]

  enum state: [:nsw, :vic, :qld]

  # enum time_of_posturing: [:3_5days, :1_week, :10_days, :1_week, :2_weeks, :3_weeks ]

  validates :email, presence: true, uniqueness: true

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :fetch_user

  def fetch_user
    # Check if the session[:user_id] is set, and also make sure it
    # contains a valid (current) user ID

    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end

    # Delete this session (clear the ID from the session hash)
    # if the ID did not return a valid user
    unless @current_user.present?
      session[:user_id] = nil
    end

  end

  def check_if_logged_in
    # Show pages can ONLY be seen by logged-in users
    redirect_to login_path unless @current_user.present?
  end

  def check_if_admin
    #
    redirect_to login_path unless @current_user.present? && @current_user.admin?
  end

end #fetch_user

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  end

  def create
    # @order = Order.find params[:order_id]
    # @comment = @order.comments.create params[:comment].permit(:name, :comment)

    # raise 'hell'
    # For future refactor
    # Use strong params
    # Hint: these can be found in the user controller e.g.
    Comment.create comment: params[:comment][:comment], order_id: params[:comment][:order_id]


    redirect_to order_path(params[:comment][:order_id])

  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    comment = Comment.find params[:id]
    comment.destroy

    redirect_to order_path(comment.order.id)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def accept
    order = Order.find params[:id]
    order.update technician_id:@current_user.id

  end

  def new
    @order = Order.new
  end

  def create
    # only patients can create orders and patients
    # when order is created the status field automatically sets to 'quoted'
    @current_user.submitted_orders.create order_params
    # , status: 'quoted'

    redirect_to orders_path

  end

  def index
    # only admin can see all orders
    # @orders = Order.all

    @unassigned_orders = Order.where technician_id:nil

    # @current_technician = Order.where technician_id: @current_user.id
  end

  def show
    @order = Order.find params[:id]

    @unassigned_orders = Order.where technician_id:nil

    @comment = Comment.new
  end

  def edit
    # Only admin and technician can edit orders
    @order = Order.find params[:id]
    # check_ownership

  end

  def update

    @order = Order.find params[:id]
    @order.update order_params

    # Do update here
    redirect_to orders_path
    # and return unless @order.patient == @current_user

    puts "~~~~~~~~~~~~~~~~ ORDER UPDATED ~~~~~~~~~~~~~~~~"

  end

  def destroy
    Order.destroy params[:id]

    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit( :item_size, :surgeon, :surgery_date, :delivery_date, :health_fund, :time_of_posturing, :health_problems, :status )
  end

  def check_ownership
    redirect_to login_path and return unless @order.user == @current_user
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    # See if the email entered actually exists in the 'users' create_table
    user = User.find_by email: params[:email]

    # Did we find a user, and if we did, is the password correct?
      if user.present? && user.authenticate(params[:password])
        # succesful login

        session[:user_id] = user.id

        redirect_to user_path(user.id) #go to show page (/users/10 or whatever ID)

      else
        # failed login (wrong credentials)
        flash[:error] = 'Invalid email or password'
        redirect_to login_path # show the form again

    end

  end #create

  def destroy
    session[:user_id] = nil #This logs out the user
    redirect_to login_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Certain pages are visible only to logged-in users:
  before_action :check_if_logged_in, except: [:new, :create]

  # Lock down admin pages
  before_action :check_if_admin, only: [:index]

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params # strong params

    if @user.persisted?
      session[:user_id] = @user.id #log them in automatically!
      redirect_to user_path(@user.id)
    else
      flash[:errors] = @user.errors.full_messages #ActiveRecord has set these errors

      render :new
    end

  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]

  end

  def update
    user = User.find params[:id]

    user = User.update user_params

    redirect_to users_path
  end

  def destroy
    User.destroy params[:id]

   redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit( :name, :dob, :contact, :email, :password, :password_confirmation, :height, :weight, :address, :state, :card_payment, :user_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vitrectomy Hire</title>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <!-- h1 -->
      <a class="navbar-brand" href=<%=root_path%> >Vitrectomy Hire</a>

      <div cclass="nav-link">

      <% if @current_user.present? %>
        Welcome, <%= @current_user.name %>


        <% if @current_user.admin? %>
        (admin)

        <%= link_to 'Users', users_path %>

        <%= link_to 'Orders', orders_path %>

        <% end %>

        <% if @current_user.technician? %>
          (technician)
        <div class="btn btn-info">
          <%= link_to 'Orders', orders_path %>
        </div>

        <% end %>

        <% if @current_user.patient? %>
        (patient)

        <div class="btn btn-info">
          <%= link_to 'Order Info', orders_path %>
        </div>

        <div class="btn btn-info">
          <%= link_to 'Create Order', new_order_path %>
        </div>

        <% end %>

        <div class="btn btn-info">
          <%= link_to 'Logout', login_path, method: 'delete' %>
        </div>

      <% else %>

      <div class="btn btn-info">
        <%= link_to 'Login', login_path %>
      </div>


      <% end %>

      </div>
    </nav>



    <%= yield %>
    <!-- <div class="footerContainer">

    <footer class="footer">

      &copy; IrenekMac Productions, 2020
    </footer>
  </div> -->

  <footer class="card-footer text-center" >
      Made With ❤ by <a href="https://github.com/irenekmac">Irene Mac</a>
    </footer>

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>

  <div class="form-group">
  <%= f.hidden_field :status, value: 'quoted' %>
    <%= f.label :equipment_size %>
    <%= f.text_field :item_size, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :surgeon %>
    <%= f.text_field :surgeon, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :surgery_date %>
    <%= f.text_field :surgery_date, :class => "form-control" %> (yyyy/mm/dd)
  </div>

  <div class="form-group">
    <%= f.label :delivery_date %>
    <%= f.text_field :delivery_date, :class => "form-control" %> (yyyy/mm/dd)
  </div>

  <div class="form-group">
    <%= f.label :health_fund %>
    <%= f.text_field :health_fund, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :time_of_posturing %>
    <%= f.select :time_of_posturing, ['Please select','3-5 days', '1 week', '10 days', '2 weeks', '3 weeks', '4 weeks' ], :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :any_health_problems? %>
    <%= f.text_field :health_problems, :class => "form-control" %>
  </div>

  <% if @current_user.technician? %>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, Order.statuses.keys.to_a, :class => "form-control" %>
  </div>


  <% end %>

  <%= f.submit 'Submit', :class => "btn btn-info btn-block my-4" %>

<% end %>

app/views/orders/edit.html.erb
<div class="card">

  <h2  class="card-title text-center">Edit Order</h2>
  <%= render partial: 'form' %>

</div>

app/views/orders/index.html.erb
<div class="card">
  <div class="card-body">

    <h2 class="card-title text-center">Your Orders</h2>


    <!-- this is a list of links to patient orders that are not yet assigned to a technician,
      can only be seen by technicians and admin so they may assign themselves to a order. -->

    <h3 class="card-title text-center">Unassigned Orders</h3>
    <ul>
      <% @unassigned_orders.each do |order| %>
      <li class="card-text text-center">
        <%= link_to " Order number #{order.id}", order_path(order.id) %>


        <!-- You only see an edit link for orders created -->
        <% if order.id == @current_user %>
        (<%= link_to 'edit', edit_order_path(order.id) %>)
      <% end %>
    </li>

    <% end %>
    </ul>

    <!-- this list can be seen by the patient who made the order -->

    <h3 class="card-title text-center">Orders Assigned To You</h3>
    <ul>
      <% @current_user.assigned_orders.each do |order| %>
      <li class="card-text text-center">
        <%= link_to " Order number #{order.id} - status: #{order.status}", order_path(order.id) %>


        <!-- You only see an edit link for orders created -->
        <% if order.id == @current_user %>
        (<%= link_to 'edit', edit_order_path(order.id) %>)
      <% end %>
    </li>

    <% end %>
    </ul>

  </div>

</div>

app/views/orders/new.html.erb
<div class="card">
  <div class="card-body">

    <h2 class="card-title text-center">New Order</h2>

    <%= render partial: 'form' %>
  </div>

</div>

app/views/orders/show.html.erb
<div class="card">
  <div class="card-body">

    <h2 class="card-title"> Order Details </h2>
    <div class="card-link">
      <%= link_to 'Edit Order', edit_order_path(@order.id) %>
      |
      <%= link_to 'Delete Order', order_path(@order.id), method: 'delete' %>
    </div>


    <p><strong>Patient ID</strong>: <%= @order.patient_id %></p>
    <p><strong>Technician ID</strong>: <%= @order.technician_id %></p>
    <p><strong>Item Size</strong>: <%= @order.item_size %></p>
    <p><strong>Order Status</strong>: <%= @order.status %></p>
    <p><strong>Time of Posturing</strong>: <%= @order.time_of_posturing %></p>
    <p><strong>Health Fund</strong>: <%= @order.health_fund %></p>
    <p><strong>Surgeon</strong>: <%= @order.surgeon %></p>
    <p><strong>Surgery Date</strong>: <%= @order.surgery_date %></p>
    <p><strong>Delivery Date</strong>: <%= @order.delivery_date %></p>
    <p><strong>Any Health Issues</strong>: <%= @order.health_problems %></p>

    <% if @current_user.technician?%>

    <p><strong>Order Status</strong>: <%= @order.status %></p>

    <% end %>

    <% if @current_user.technician? %> <!-- only technician users can see this button -->

    <% if @unassigned_orders %> <!-- this button only appears if the technician_id:'nil' -->
    <%= button_to 'Accept this Order', order_accept_path(@order.id), :class => "btn btn-outline-primary btn-block my-4" %>
    <% end %>

    <% end %>

    <!-- comments section -->

        <%= form_for @comment do |f| %>

        <%= f.label :Messages, :for => "comment" %>
        <br>
        <%= f.text_area :comment, :class => "form-control", :rows => "3" %>
        <br>

        <%= f.hidden_field :order_id, :value => @order.id%>

        <%= f.submit 'Submit', :class => "btn btn-primary" %>

        <% end %>

        <!-- Messages/Comments -->
        <% @order.comments.each do |c| %>

        <li class="listedComment">
          <%= c.comment %>
        </li>

          <%= link_to 'Delete', comment_path(c.id), method: 'delete', :class => "comment-meta" %>

        <% end %>

  </div> <!-- card body -->

</div> <!-- card -->

app/views/session/new.html.erb
<!-- Login Form -->
<div class="login-form text-center">

<%= form_tag login_path, class: 'border border-light p-5' do %>
  <p class="h4 mb-4 text-center">Log In</p>

  <!-- Print out error msg if the user is not present -->
  <% if flash[:error].present? %>
  <p class="alert alert-danger p-2 text-center"><%= flash[:error] %></p>
  <% end %>

  <!-- Email -->
  <%= label_tag :email %>
  <%= email_field_tag :email, 'ian@test.co', :class => "form-control mb-4" %>

  <!-- Password -->
  <%= label_tag :password %>
  <%= password_field_tag :password, 'chicken', :class => "form-control mb-4" %>

  <!-- Login button -->
  <%= submit_tag "Log In", :class => "btn btn-info btn-block my-4" %>

  <!-- Sign Up -->
  <p class="text-center">
    Don't have an account?
    <%= link_to "Sign Up", new_user_path %>
  </p>

<% end %>

</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <div class="form-group">
    <%= f.label :user_type, :for => "exampleFormControlSelect1" %>
    <%= f.select :user_type, User.user_types.keys.to_a, :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :full_name %>
    <%= f.text_field :name, :class => "form-control mb-4" %>
  </div>

  <div class="form-group">
    <%= f.label :date_of_birth %> (yyyy/mm/dd)
    <%= f.text_field :dob, :class => "form-control mb-4" %>
  </div>

  <div class="form-group">
    <%= f.label :contact_number %>
    <%= f.text_field :contact, :class => "form-control mb-4" %>
  </div>

  <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, :type => "exampleInputEmail1", :class => "form-control" %>
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-control mb-4" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "form-control mb-4" %>
  </div>

  <div class="form-group">
    <%= f.label :height %> (cm)
    <%= f.text_field :height, :class => "form-control mb-4" %>
  </div>

  <div class="form-group">
    <%= f.label :weight %> (kg)
    <%= f.text_field :weight, :class => "form-control mb-4" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, :class => "form-control mb-4" %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.select :state, User.states.keys.to_a %>
  </div>

  <div class="form-group">
    <%= f.label :card_payment %>
    <%= f.text_field :card_payment, :class => "form-control mb-4" %>
  </div>

  <%= f.submit 'Submit', :class => "btn btn-info btn-block my-4" %>

<% end %>

app/views/users/edit.html.erb
<div class="card">

  <h2  class="card-title text-center">Edit Account</h2>

  <%= render partial: 'form' %>

</div>

app/views/users/index.html.erb
<h2>
  All Users
</h2>

<ul>
  <% @users.each do |user| %>
  <li>
    <!-- loop lists all the users and gives ea user a link, when clicked it
    sends you to the show page that lists the users' db info -->
    <%= link_to user.name, user_path(user.id) %>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="card">
  <div class="card-body">

    <h2 class="card-title text-center">Create New Account</h2>

  <% if @user.errors.any? %>
  <p>Please correct the following errors:</p>
  <ul>
    <% @user.errors.full_messages.each do |e| %>

    <li><%= e %></li>

    <% end %>
  </ul>
    <% end %>

  <%= render partial: 'form' %>
</div>

</div>

app/views/users/show.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title"> <%= @user.name %> </h2>
    <div class="card-link">
      <%= link_to 'Edit Account', edit_user_path(@user.id) %>
      |
      <%= link_to 'Delete Account', user_path(@user.id), method: 'delete' %>
    </div>

    <p><strong>User Type</strong>: <%= @user.user_type %></p>
    <p><strong>Full Name</strong>: <%= @user.name %></p>
    <p><strong>Date of Birth</strong>: <%= @user.dob %></p>
    <p><strong>Height</strong>: <%= @user.height %> cm </p>
    <p><strong>Weight</strong>: <%= @user.weight %> kg </p>
    <p><strong>Email Address</strong>: <%= @user.email %></p>
    <p><strong>Contact Number</strong>: <%= @user.contact %></p>
    <p><strong>Address</strong>: <%= @user.address %></p>
    <p><strong>State</strong>: <%= @user.state %></p>
    <p><strong>Card Details</strong>: <%= @user.card_payment %></p>
    <p><strong>Card Verified</strong>: <%= @user.card_verified %></p>

  </div>

</div>